project:
  name: tech
  project_root_path: C:\Users\anson\dev\video-publisher\video_publiser_data\bilibili\projects\tech
  creation_mode: auto
  description: ''
  platforms: []
publish_defaults:
  title_format: '{video_name}'
  description_format: ''
  tags: []
  partition: ''
  auto_cover: true
material:
  video_source_dir: ''
cover:
  comfyui_workflow: ''
  prompt: ''
  width: 1920
  height: 1080
  seed: 0
  negative_prompt: ''
dependence_paths:
  comfyui_scheduler: ''
  comfyui_url: http://127.0.0.1:8188
